### ISSUE TITLE
Migrate to 'surreal'

### ISSUE THREAD

**Issue by DrewRidley** [siteforge-io/surreal-codegen#1]
At the moment, the generated script seems to import 'surrealdb.js' but this has been deprecated in favor of surreal. It is not possible to connect to a 2.0 instance without explicitly using beta 18.

The generated code should be updated accordingly.
Thanks!

**Comment by AlbertMarashi** [comment]
@DrewRidley good point, it is actually possible to override the header, if you run `surreal-codegen` you will receive information on how to do that.

I will update the code accordingly however

**Comment by AlbertMarashi** [comment]
@DrewRidley  I've closed this issue with a fix and you can read the documentation for updating the header in case you were curious or need to override the default class instance, or update to the latest version.
